[SERVICE]
    flush        1
    daemon       off
    log_level    info
    parsers_file parsers.conf

# =============================================================
# INPUTS
# =============================================================

# 1. Input untuk log web aplikasi (JSON) di VM1
[INPUT]
    name             tail
    path             /root/cloud-backend/logs/cloud-backend.log
    parser           json
    tag              labpro.app.logs
    refresh_interval 5
    mem_buf_limit    5mb
    skip_long_lines  on

# 2. Input untuk log kluster Ceph (Regex parser)
[INPUT]
    name             tail
    path             /var/log/ceph/*/ceph.log
    parser           ceph
    tag              labpro.ceph.logs
    refresh_interval 5
    mem_buf_limit    5mb
    skip_long_lines  on

# =============================================================
# OUTPUTS (Kedua output dikirim ke OpenSearch lokal di VM1)
# =============================================================

# 1. Output untuk log web aplikasi ke OpenSearch
[OUTPUT]
    name            opensearch
    match           labpro.app.logs
    host            127.0.0.1
    port            9200
    http_user       admin
    http_passwd     admin
    index           labpro-web-logs
    type            _doc
    tls             on
    tls.verify      off
    suppress_type_name on

# 2. Output untuk log kluster Ceph ke OpenSearch
[OUTPUT]
    name            opensearch
    match           labpro.ceph.logs
    host            127.0.0.1
    port            9200
    http_user       admin
    http_passwd     admin
    index           labpro-ceph-logs
    type            _doc
    tls             on
    tls.verify      off
    suppress_type_name on
