[SERVICE]
    flush        1
    daemon       off
    log_level    info
    parsers_file parsers.conf

# -------------------------------------------------------------
# INPUTS
# -------------------------------------------------------------

# Input untuk log web aplikasi (JSON)
[INPUT]
    name             tail
    path             ./logs/cloud-backend.log
    parser           json
    tag              labpro.app.logs
    refresh_interval 5
    mem_buf_limit    5mb
    skip_long_lines  on

# -------------------------------------------------------------
# OUTPUTS
# -------------------------------------------------------------

# Output untuk log web aplikasi ke OpenSearch
[OUTPUT]
    name            opensearch
    match           labpro.app.logs
    host            100.68.13.84
    port            9200
    http_user       admin
    http_passwd     admin
    index           labpro-web-logs
    type            _doc
    tls             on
    tls.verify      off
    suppress_type_name on
