[SERVICE]
    flush        1
    daemon       off
    log_level    info
    parsers_file parsers.conf

[INPUT]
    name             tail
    path             ./logs/cloud-backend.log
    parser           json
    tag              labpor.app.logs
    refresh_interval 5
    mem_buf_limit    5mb
    skip_long_lines  on

[OUTPUT]
    name            opensearch
    match           labpor.*
    host            192.168.100.53
    port            9200
    http_user       admin
    http_passwd     LabproCephLogging2026!
    index           labpor-web-logs
    type            _doc
    tls             on
    tls.verify      off
    suppress_type_name on
