[PARSER]
    Name        json
    Format      json
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On

[PARSER]
    Name        ceph
    Format      regex
    Regex       ^(?<time>[^ ]+) (?<entity>[^ ]+) \((?<daemon>[^)]+)\) (?<seq>\d+) : (?<subsystem>[^ ]+) \[(?<priority>[^\]]+)\] (?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On
